-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 12:15:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

--! IN CASE OF ERRORS, PLEASE REMOVE ANY "VISIBLE" STATMENT,
--! TRY AGAIN AND SEE IF IT WORKS NOW



CREATE SCHEMA IF NOT EXISTS `martin` DEFAULT CHARACTER SET utf8mb4 ;
USE `martin` ;

-- -----------------------------------------------------
-- Table `martin`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `martin`.`articulos` ;

CREATE TABLE IF NOT EXISTS `martin`.`articulos` (
  `articulos_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`articulos_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `martin`.`carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `martin`.`carrito` ;

CREATE TABLE IF NOT EXISTS `martin`.`carrito` (
  `id_carrito` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` TINYINT(30) NOT NULL,
  PRIMARY KEY (`id_carrito`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `martin`.`pivot_carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `martin`.`pivot_carrito` ;

CREATE TABLE IF NOT EXISTS `martin`.`pivot_carrito` (
  `PK_pivotCarrito` INT(11) NOT NULL AUTO_INCREMENT,
  `id_carrito` INT(11) NOT NULL,
  `id_articulos` INT(11) NOT NULL,
  PRIMARY KEY (`PK_pivotCarrito`),
  CONSTRAINT `fk_carrito_has_articulos_articulos1`
    FOREIGN KEY (`id_articulos`)
    REFERENCES `martin`.`articulos` (`articulos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_articulos_carrito1`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `martin`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_carrito_has_articulos_articulos1_idx` ON `martin`.`pivot_carrito` (`id_articulos` ASC) VISIBLE;

CREATE INDEX `fk_carrito_has_articulos_carrito1_idx` ON `martin`.`pivot_carrito` (`id_carrito` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `martin`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `martin`.`user` ;

CREATE TABLE IF NOT EXISTS `martin`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `carrito_id` INT(11) NOT NULL,
  `imagen` VARCHAR(50) NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `role` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_carrito1`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `martin`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `mail_UNIQUE` ON `martin`.`user` (`mail` ASC) VISIBLE;

CREATE UNIQUE INDEX `carrito_id_UNIQUE` ON `martin`.`user` (`carrito_id` ASC) VISIBLE;

CREATE INDEX `fk_user_carrito1_idx` ON `martin`.`user` (`carrito_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
